name:                editor-hs
version:             0.1.0.0
github:              "sullyj3/editor-hs"
license:             BSD3
author:              "James Sully"
maintainer:          "sullyj3@gmail.com"
copyright:           "(c) 2021 James Sully"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sullyj3/editor-hs#readme>

dependencies:
- relude
- base >= 4.7 && < 5
- microlens
- microlens-th
- containers
- text
- vty
- mtl
- flow

library:
  source-dirs: src

executables:
  editor-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - editor-hs

tests:
  editor-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - editor-hs
